# Numpy Review (The Important Bits)

In [3]:
import numpy as np

## Creation

In [4]:
a = np.zeros((2,2))      # Create an array of zeros
print("a:\n",a)

b = np.ones((2,2))       # Create an array of ones
print("b:\n",b)

d = np.eye(2)            # Create a 2x2 identity matrix
print("d:\n",d)

e = np.random.random((3,3)) # Create random element matrix (0,1)
print("e:\n",e)  

f = np.arange(2, 3, 0.1) # elements 2-3 with step size 0.1
print("f:\n",f)

g = np.linspace(1., 4., 6) # elements 1-4 with 6 steps
print("g:\n",g)

a:
 [[0. 0.]
 [0. 0.]]
b:
 [[1. 1.]
 [1. 1.]]
d:
 [[1. 0.]
 [0. 1.]]
e:
 [[0.0126604  0.28318552 0.23578547]
 [0.495095   0.90193642 0.77576448]
 [0.65470534 0.21506009 0.01720476]]
f:
 [2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
g:
 [1.  1.6 2.2 2.8 3.4 4. ]


# Functions

In [28]:
x = np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
x ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [30]:
np.cos(x)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153])

In [31]:
np.sin(x)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [32]:
np.exp(x)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

# Reshape

In [10]:
x = np.arange(1,16)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [13]:
y = x.reshape((-1, 5))
y

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

# Statistical Functions

* With these functions we can use the `axis` parameter.
    * `x.mean()`: takes the mean of the whole data set
    * `x.mean(axis=0)`: takes the mean of each row
    * `x.mean(axis=1)`: takes the mean of each column

In [19]:
x = np.arange(1,16)
x = x.reshape((-1, 5))
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [20]:
x.mean()

8.0

In [21]:
x.mean(axis=0) # along each column

array([ 6.,  7.,  8.,  9., 10.])

In [22]:
x.mean(axis=1) # along each row

array([ 3.,  8., 13.])

In [23]:
x.sum()

120

In [26]:
print("np.sum(x)", np.sum(x))
print("np.std(x)", np.std(x))
print("np.var(x)", np.var(x))
print("np.median(x)",np.median(x))

np.sum(x) 120
np.std(x) 4.320493798938574
np.var(x) 18.666666666666668
np.median(x) 8.0


* alternatively, we can **often** use the dot notation for these functions.

In [25]:
print("x.sum()",x.sum())
print("x.std()",x.std())
print("x.var()",x.var())
print("x.median()",np.median(x))

x.sum() 120
x.std() 4.320493798938574
x.var() 18.666666666666668
x.median() 8.0
